2024-03-15T09:52:23 {"cpu": 0.30908203125, "cpu_total": 2, "cpu_usage": 0.154541015625, "memory": 2856.0, "memory_total": 7929.0, "memory_usage": 0.3601967461218313, "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Pipeline export_to_big_query for run 4 in schedule 2 is alive.", "timestamp": 1710496343.893605, "uuid": "08e31f01c7bd40ee82eb7068f102f464"}
2024-03-15T09:52:24 {"block_run_id": 31, "block_uuid": "load_customer_dimension", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 31: pipeline export_to_big_query block load_customer_dimension", "timestamp": 1710496344.309967, "uuid": "286c9fb7c7ab40c7b8e8b4aad3e4fc12"}
2024-03-15T09:52:24 {"cpu": 0.30908203125, "cpu_total": 2, "cpu_usage": 0.154541015625, "memory": 2907.0, "memory_total": 7929.0, "memory_usage": 0.36662883087400683, "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Pipeline export_to_big_query for run 4 in schedule 2 is alive.", "timestamp": 1710496344.746527, "uuid": "2994d673d42d4fda81ab1d0aec49f6b1"}
2024-03-15T09:52:25 {"block_run_id": 33, "block_uuid": "load_department_dimension", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 33: pipeline export_to_big_query block load_department_dimension", "timestamp": 1710496345.385673, "uuid": "5333f6b8c3524526a8d0e32f8cc94b9f"}
2024-03-15T09:52:25 {"block_run_id": 35, "block_uuid": "load_location_dimension", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 35: pipeline export_to_big_query block load_location_dimension", "timestamp": 1710496345.530739, "uuid": "3f4c5307ec714de08adbec260c85db0c"}
2024-03-15T09:52:25 {"block_run_id": 38, "block_uuid": "load_metadata_dimensio", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 38: pipeline export_to_big_query block load_metadata_dimensio", "timestamp": 1710496345.549847, "uuid": "1472f56244d4496b982132edb22bf65f"}
2024-03-15T09:52:25 {"block_run_id": 39, "block_uuid": "load_order_dimension", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 39: pipeline export_to_big_query block load_order_dimension", "timestamp": 1710496345.612894, "uuid": "5ac0054c9ca545bc99eeb93d312e791b"}
2024-03-15T09:52:25 {"block_run_id": 41, "block_uuid": "load_product_dimension", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 41: pipeline export_to_big_query block load_product_dimension", "timestamp": 1710496345.622176, "uuid": "f9269542049f4476a1fe4ad6ceec56be"}
2024-03-15T09:52:25 {"block_run_id": 43, "block_uuid": "load_shipping_dimension", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 43: pipeline export_to_big_query block load_shipping_dimension", "timestamp": 1710496345.734222, "uuid": "f4f5d2dc23f8484d83282bc7ede7be01"}
2024-03-15T09:52:31 {"block_run_id": 33, "block_uuid": "load_department_dimension", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 33 (block_uuid: load_department_dimension) completes.", "timestamp": 1710496351.183996, "uuid": "44eda8dc1c9d400a843c02fa1e66e719"}
2024-03-15T09:52:33 {"block_run_id": 31, "block_uuid": "load_customer_dimension", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 31 (block_uuid: load_customer_dimension) completes.", "timestamp": 1710496353.14947, "uuid": "46b7d14e28db4fa9a264e68ca602e713"}
2024-03-15T09:52:34 {"cpu": 0.3271484375, "cpu_total": 2, "cpu_usage": 0.16357421875, "memory": 3621.0, "memory_total": 7929.0, "memory_usage": 0.4566780174044646, "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Pipeline export_to_big_query for run 4 in schedule 2 is alive.", "timestamp": 1710496354.193037, "uuid": "b7736ba90d8b4c6699bc14fba048bd15"}
2024-03-15T09:52:34 {"block_run_id": 35, "block_uuid": "load_location_dimension", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 35 (block_uuid: load_location_dimension) completes.", "timestamp": 1710496354.367873, "uuid": "3a23341a749c49b79ca316261b1a6b84"}
2024-03-15T09:52:34 {"block_run_id": 38, "block_uuid": "load_metadata_dimensio", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 38 (block_uuid: load_metadata_dimensio) completes.", "timestamp": 1710496354.422282, "uuid": "cd49555bff8946aa9e29b2cc2fd7d736"}
2024-03-15T09:52:35 {"block_run_id": 32, "block_uuid": "customer_dim_to_big_query", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 32: pipeline export_to_big_query block customer_dim_to_big_query", "timestamp": 1710496355.843226, "uuid": "9f241d0788494057b3ff32cd93d4bb15"}
2024-03-15T09:52:35 {"block_run_id": 36, "block_uuid": "location_dim_to_big_query", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 36: pipeline export_to_big_query block location_dim_to_big_query", "timestamp": 1710496355.869467, "uuid": "7b88928458ee43ce9d19d3a9eeb6875d"}
2024-03-15T09:52:35 {"block_run_id": 34, "block_uuid": "department_dim_to_big_query", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 34: pipeline export_to_big_query block department_dim_to_big_query", "timestamp": 1710496355.887775, "uuid": "0a21918b77ea40f59fb1fb66f9fcec25"}
2024-03-15T09:52:36 {"block_run_id": 37, "block_uuid": "metadata_dim_to_big_query", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 37: pipeline export_to_big_query block metadata_dim_to_big_query", "timestamp": 1710496356.012836, "uuid": "6caea75d8c6b419cba302f7b05ef1a04"}
2024-03-15T09:52:37 {"block_run_id": 41, "block_uuid": "load_product_dimension", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 41 (block_uuid: load_product_dimension) completes.", "timestamp": 1710496357.206142, "uuid": "31d6e47625a64f6c86965cf54b3903a9"}
2024-03-15T09:52:37 {"block_run_id": 43, "block_uuid": "load_shipping_dimension", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 43 (block_uuid: load_shipping_dimension) completes.", "timestamp": 1710496357.824527, "uuid": "472114320a2240769504dcc50101dbe8"}
2024-03-15T09:52:38 {"block_run_id": 39, "block_uuid": "load_order_dimension", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 39 (block_uuid: load_order_dimension) completes.", "timestamp": 1710496358.148534, "uuid": "35dc88f573734ecda726214876a53366"}
2024-03-15T09:52:43 {"cpu": 0.37744140625, "cpu_total": 2, "cpu_usage": 0.188720703125, "memory": 3661.0, "memory_total": 7929.0, "memory_usage": 0.46172278975911213, "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Pipeline export_to_big_query for run 4 in schedule 2 is alive.", "timestamp": 1710496363.897908, "uuid": "37669afeda8c4efda7f82b656172b9c7"}
2024-03-15T09:52:44 {"block_run_id": 40, "block_uuid": "order_dim_to_big_query", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 40: pipeline export_to_big_query block order_dim_to_big_query", "timestamp": 1710496364.868456, "uuid": "d58ddb398bbd4a16ae085f0c8a7d4132"}
2024-03-15T09:52:44 {"block_run_id": 42, "block_uuid": "product_dim_to_big_query", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 42: pipeline export_to_big_query block product_dim_to_big_query", "timestamp": 1710496364.875745, "uuid": "ca5e35dd863c4dc6bc81aa185a87e6a3"}
2024-03-15T09:52:44 {"block_run_id": 44, "block_uuid": "shipping_dim_to_big_query", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 44: pipeline export_to_big_query block shipping_dim_to_big_query", "timestamp": 1710496364.927789, "uuid": "4ee0b149c69d439d97da6e1209d351d8"}
2024-03-15T09:52:46 {"block_run_id": 34, "block_uuid": "department_dim_to_big_query", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 34 (block_uuid: department_dim_to_big_query) completes.", "timestamp": 1710496366.243582, "uuid": "9c1db0326e7f4ed29ad6037659d09c6c"}
2024-03-15T09:52:48 {"block_run_id": 36, "block_uuid": "location_dim_to_big_query", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 36 (block_uuid: location_dim_to_big_query) completes.", "timestamp": 1710496368.756334, "uuid": "9552570a41af4cd996741ea3a46afe77"}
2024-03-15T09:52:49 {"block_run_id": 32, "block_uuid": "customer_dim_to_big_query", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 32 (block_uuid: customer_dim_to_big_query) completes.", "timestamp": 1710496369.713954, "uuid": "bd3230b8653141688207ad94b395f9c4"}
2024-03-15T09:52:50 {"block_run_id": 37, "block_uuid": "metadata_dim_to_big_query", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "BlockRun 37 (block_uuid: metadata_dim_to_big_query) completes.", "timestamp": 1710496370.801727, "uuid": "d0016e00573444d2bac54468a7333a1a"}
2024-03-15T09:52:52 {"block_run_id": 44, "block_uuid": "shipping_dim_to_big_query", "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "EXCEPTION", "message": "BlockRun 44 (block_uuid: shipping_dim_to_big_query) failed.", "timestamp": 1710496372.106273, "uuid": "f1a46ac9ed8c4ff3a0680145275331e1", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 2491, in load_table_from_file\n    response = self._do_multipart_upload(\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 3046, in _do_multipart_upload\n    response = upload.transmit(\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py\", line 153, in transmit\n    return _request_helpers.wait_and_retry(\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py\", line 155, in wait_and_retry\n    response = func()\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py\", line 149, in retriable_request\n    self._process_response(result)\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/_upload.py\", line 125, in _process_response\n    _helpers.require_status_code(response, (http.client.OK,), self._get_status_code)\n  File \"/usr/local/lib/python3.10/site-packages/google/resumable_media/_helpers.py\", line 108, in require_status_code\n    raise common.InvalidResponse(\ngoogle.resumable_media.common.InvalidResponse: ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1315, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1224, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1530, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1686, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1725, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 23, in export_data_to_big_query\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 319, in export\n    __process(database=database)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 315, in __process\n    self.client.load_table_from_dataframe(df, table_id, job_config=config).result()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 2727, in load_table_from_dataframe\n    return self.load_table_from_file(\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py\", line 2495, in load_table_from_file\n    raise exceptions.from_http_response(exc.response)\ngoogle.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gothic-sylph-387906/jobs?uploadType=multipart: Invalid field name \"Days_for_shipping_(real)\". Fields must contain the allowed characters, and be at most 300 characters long. For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 743, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1615, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 190, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 602, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1152, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 433, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gothic-sylph-387906/jobs?uploadType=multipart: Invalid field name \"Days_for_shipping_(real)\". Fields must contain the allowed characters, and be at most 300 characters long. For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 2491, in load_table_from_file
    response = self._do_multipart_upload(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 3046, in _do_multipart_upload
    response = upload.transmit(
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py", line 153, in transmit
    return _request_helpers.wait_and_retry(
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py", line 149, in retriable_request
    self._process_response(result)
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/_upload.py", line 125, in _process_response
    _helpers.require_status_code(response, (http.client.OK,), self._get_status_code)
  File "/usr/local/lib/python3.10/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1315, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1224, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1530, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1686, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1725, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 23, in export_data_to_big_query
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 319, in export
    __process(database=database)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 315, in __process
    self.client.load_table_from_dataframe(df, table_id, job_config=config).result()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 2727, in load_table_from_dataframe
    return self.load_table_from_file(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 2495, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gothic-sylph-387906/jobs?uploadType=multipart: Invalid field name "Days_for_shipping_(real)". Fields must contain the allowed characters, and be at most 300 characters long. For allowed characters, please refer to https://cloud.google.com/bigquery/docs/schemas#column_names
2024-03-15T09:52:53 {"cpu": 0.37255859375, "cpu_total": 2, "cpu_usage": 0.186279296875, "memory": 3464.0, "memory_total": 7929.0, "memory_usage": 0.4368772859124732, "pipeline_run_id": 4, "pipeline_schedule_id": 2, "pipeline_uuid": "export_to_big_query", "hostname": "d2d72e4b77ea", "level": "INFO", "message": "Pipeline export_to_big_query for run 4 in schedule 2 is alive.", "timestamp": 1710496373.340438, "uuid": "9bfc4ec76a3947e8bbdee2d9e667b149"}
